# Generated by Django 4.0.4 on 2022-05-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_shoes_descriptionshoes_shoes_imageshoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoes',
            name='imageShoes',
        ),
    ]
